name: Split Monorepo

on:
  push:
    tags:
      - '*'
    branches:
      - '1.0'

jobs:
  split_monorepo:
    name: Split Monorepo
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        # define package to repository map
        package:
          - local_path: 'Test'
            split_repository: 'test2'

    steps:
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package }}
        uses: "msmakouz/monorepo-split-github-action@2.2.1"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: ${{ github.ref_name }}
          package_directory: 'src/${{ matrix.package.local_path }}'
          repository_organization: 'msmakouz'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: "msmakouz/monorepo-split-github-action@2.2.1"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          branch: ${{ github.ref_name }}
          package_directory: 'src/${{ matrix.package.local_path }}'
          repository_organization: 'msmakouz'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
